taco:
  orders:
    pageSize: 12

logging:
  level:
    tacos: DEBUG

spring:
  data:
    rest:
      base-path: /api
  jms:
    template:
      default-destination: tcp://localhost:8089
  application:
    name: taco_cloud

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword
logging:
  level:
    tacos: WARN
